STIVE.CL/STIVE.CL/Pages/Admin.cshtml.cs
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using STIVE.CL.DTOs;
using STIVE.CL.Services;

namespace STIVE.CL.Pages;

public class AdminModel : PageModel
{
    private readonly ApiService _apiService;
    public string TableToRender { get; set; }
    public List<UserDto> Users { get; set; }
    public List<RoleDto> Roles { get; set; }
    public List<GameDataDto> GameDatas { get; set; }
    public List<BonusDto> Bonuses { get; set; }
    public List<PotionDto> Potions { get; set; }
    public List<SupplierDto> Suppliers { get; set; }
    public List<CustomerDto> Customers { get; set; }

    private readonly HttpClient _httpClient;

    public AdminModel(ApiService apiService)
    {
        _apiService = apiService;
    }

    public async Task OnGetAsync(string table = "users")
    {
        TableToRender = table;
        string baseUrl = "http://localhost:5294/api/";
        
        switch (TableToRender)
        {
            case "users":
                Users = await _apiService.GetListAsync<UserDto>($"{baseUrl}User/getAll");
                break;
            case "roles":
                Roles = await _apiService.GetListAsync<RoleDto>($"{baseUrl}Role/getAll");
                break;
            case "gamedatas":
                GameDatas = await _apiService.GetListAsync<GameDataDto>($"{baseUrl}GameData/getAll");
                break;
            case "bonus":
                Bonuses = await _apiService.GetListAsync<BonusDto>($"{baseUrl}Bonus/getAll");
                break;
            case "potions":
                Potions = await _apiService.GetListAsync<PotionDto>($"{baseUrl}Potion/getAll");
                break;
            case "suppliers":
                Suppliers = await _apiService.GetListAsync<SupplierDto>($"{baseUrl}Supplier/getAll");
                break;
            case "customers":
                Customers = await _apiService.GetListAsync<CustomerDto>($"{baseUrl}Customer/getAll");
                break;
        }
    }
    
    public async Task<IActionResult> OnPostDeleteAsync(string id, string type)
    {
        if (string.IsNullOrEmpty(id))
        {
            ModelState.AddModelError("", "ID invalide.");
            return Page();
        }
        
        string baseUrl = "http://localhost:5294/api/";
        
        string? url = type switch
        {
            "user" => $"{baseUrl}User/delete/{id}",
            "role" => $"{baseUrl}Role/delete/{id}",
            "gamedata" => $"{baseUrl}GameData/delete/{id}",
            "bonus" => $"{baseUrl}Bonus/delete/{id}",
            "potion" => $"{baseUrl}Potion/delete/{id}",
            "supplier" => $"{baseUrl}Supplier/delete/{id}",
            "customers" => $"{baseUrl}Customer/delete/{id}",
            _ => null
        };

        if (url == null)
            return Page();
        
        if (await _apiService.DeleteAsync(url))
        {
            TempData["Message"] = $"{type} supprimé avec succès.";
            return RedirectToPage(new { table = type + "s" });
        }
        else
        {
            TempData["Error"] = $"Erreur lors de la suppression du {type}.";
            return RedirectToPage(new { table = type + "s" });
        }
    }
}

STIVE.CL/STIVE.CL/Pages/Boutique.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace STIVE.CL.Pages;

public class BoutiqueModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public BoutiqueModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }
    public void OnGet()
    {
        
    }
}

STIVE.CL/STIVE.CL/Pages/Cart.cshtml.cs
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using STIVE.CL.DTOs;

namespace STIVE.CL.Pages;

public class CartModel : PageModel
{
    private readonly HttpClient _httpClient;

    public CartModel(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }
    public List<CartDto> UserCarts { get; set; } = new List<CartDto>();
    [BindProperty]
    public string UserId { get; set; }
    [BindProperty]
    public int BonusId { get; set; }
    [BindProperty]
    public int GameDataId { get; set; }


    public async Task<IActionResult> OnGetAsync()
    {
        UserId = "1f43468c-c467-4cdd-a02d-29bd888e09c8";
        
        var cartsResponse = await _httpClient.GetAsync($"http://localhost:5294/api/Cart/getByUserId/{UserId}");
        if (cartsResponse.IsSuccessStatusCode)
        {
            var cartsJson = await cartsResponse.Content.ReadAsStringAsync();
            UserCarts = JsonSerializer.Deserialize<List<CartDto>>(cartsJson, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
        }

        return Page();
    }
    
    public async Task<IActionResult> OnPostRemoveItemAsync()
    {
        var requestData = new { userId = UserId, bonusId = BonusId, gameDataId = GameDataId };
        var json = JsonSerializer.Serialize(requestData);
        var content = new StringContent(json, Encoding.UTF8, "application/json");

        var response = await _httpClient.PostAsync("http://localhost:5294/api/Cart/remove", content);

        if (!response.IsSuccessStatusCode)
        {
            ModelState.AddModelError(string.Empty, "Erreur lors de la suppression.");
        }

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostClearCartAsync()
    {
        var requestData = new { userId = UserId, gameDataId = GameDataId };
        var json = JsonSerializer.Serialize(requestData);
        var content = new StringContent(json, Encoding.UTF8, "application/json");

        var request = new HttpRequestMessage(HttpMethod.Delete, "http://localhost:5294/api/Cart/clear")
        {
            Content = content
        };
        
        var response = await _httpClient.SendAsync(request);
        if (!response.IsSuccessStatusCode)
        {
            ModelState.AddModelError(string.Empty, "Erreur lors de la suppression.");
        }

        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostValidateAsync()
    {
        var requestData = new { userId = UserId, gameDataId = GameDataId };
        var json = JsonSerializer.Serialize(requestData);
        var content = new StringContent(json, Encoding.UTF8, "application/json");

        var response = await _httpClient.PostAsync("http://localhost:5294/api/Cart/validate", content);

        if (!response.IsSuccessStatusCode)
        {
            ModelState.AddModelError(string.Empty, "Erreur lors de la suppression.");
        }

        return RedirectToPage();
    }
}

STIVE.CL/STIVE.CL/Pages/Classement.cshtml.cs
using System.Text.Json;
using System.Net.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace STIVE.CL.Pages;

public class ClassementModel : PageModel
{
    private readonly HttpClient _httpClient;

    public ClassementModel(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }
    
    public List<UserGold>? Users { get; set; }
    
    public async Task OnGetAsync()
    {
        HttpResponseMessage response = await _httpClient.GetAsync("http://localhost:5294/api/User/getUserGold");
        if (response.IsSuccessStatusCode)
        {
            var jsonResponse = await response.Content.ReadAsStringAsync();
            Users = JsonSerializer.Deserialize<List<UserGold>>(jsonResponse, new JsonSerializerOptions
            {
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
                PropertyNameCaseInsensitive = true
            });
        }
        else
        {
            Users = new List<UserGold>();
        }
    }

    public class UserGold
    {
        public string UserName { get; set; }
        public int Gold { get; set; }
    }
}

STIVE.CL/STIVE.CL/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace STIVE.CL.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

STIVE.CL/STIVE.CL/Pages/Game.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace STIVE.CL.Pages;

public class GameModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public GameModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }
    public void OnGet()
    {
        
    }
}

STIVE.CL/STIVE.CL/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

namespace STIVE.CL.Pages;

public class IndexModel : PageModel
{
    private readonly HttpClient _httpClient;

    public IndexModel(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }
    
    public int UserCount { get; set; }
    
    public async Task OnGetAsync()
    {
        HttpResponseMessage response = await _httpClient.GetAsync("http://localhost:5294/api/User/count");
        if (response.IsSuccessStatusCode)
        {
            var jsonResponse = await response.Content.ReadAsStringAsync();
            UserCount = JsonSerializer.Deserialize<int>(jsonResponse);
        }
        else
        {
            UserCount = 0;
        }
    }
}

STIVE.CL/STIVE.CL/Pages/Login.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace STIVE.CL.Pages;

public class LoginModel : PageModel
{
    private readonly HttpClient _httpClient;

    public LoginModel(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    [BindProperty] 
    public UserLoginDto userLoginDto { get; set; }
    public string ErrorMessage { get; set; }
    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
            return Page();
        
        var loginData = new { userLoginDto.UserName, userLoginDto.Password };

        using (var client = new HttpClient())
        {
            client.BaseAddress = new Uri("http://localhost:5294/api/User/");
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            var content = new StringContent(JsonSerializer.Serialize(loginData), Encoding.UTF8, "application/json");

            HttpResponseMessage response = await client.PostAsync("login", content);

            if (response.IsSuccessStatusCode)
            {
                var responseData = JsonSerializer.Deserialize<ResponseModel>(await response.Content.ReadAsStringAsync(),
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

                if (responseData != null && !string.IsNullOrEmpty(responseData.Token))
                {
                    Response.Cookies.Append("jwt", responseData.Token, new CookieOptions
                    {
                        HttpOnly = true,
                        Secure = true,
                        Expires = DateTime.UtcNow.AddHours(1)
                    });
                    return Redirect("/Index");
                }
            }
            else
            {
                ErrorMessage = "Invalid username or password.";
            }
        }

        return Page();
    }
}

public class UserLoginDto
{
    [Required(ErrorMessage = "Le nom est requise.")]
    public string UserName { get; set; }
    [Required(ErrorMessage = "Le mot de passe est requis.")]
    [DataType(DataType.Password)]
    public string Password { get; set; }
}

public class ResponseModel
{
    public string UserName { get; set; }
    public string[] Roles { get; set; }
    public string Token { get; set; }
}

STIVE.CL/STIVE.CL/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace STIVE.CL.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

STIVE.CL/STIVE.CL/Pages/Register.cshtml.cs
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using STIVE.CL.DTOs;

namespace STIVE.CL.Pages;

public class RegisterModel : PageModel
{
    private readonly HttpClient httpClient;

    public RegisterModel(HttpClient httpClient)
    {
        this.httpClient = httpClient;
    }
    [BindProperty]
    public UserRegisterDto UserRegister { get; set; }
    
    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }
        var json = JsonSerializer.Serialize(UserRegister);
        var content  = new StringContent(json, Encoding.UTF8, "application/json");
        var response = await httpClient.PostAsync("http://localhost:5294/api/User/register", content);
        if (response.IsSuccessStatusCode)
        {
            return RedirectToPage("/Login");
        }
        ModelState.AddModelError(string.Empty, "Un problème est survenu, veuillez rééessayer.");
        return Page();
    }
}

STIVE.CL/STIVE.CL/Pages/Shop.cshtml.cs
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using STIVE.CL.DTOs;

namespace STIVE.CL.Pages;

public class ShopModel : PageModel
{
    private readonly HttpClient _httpClient;

    public ShopModel(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }
    
    public List<BonusDto> Bonus { get; set; } = new List<BonusDto>();
    public List<GameDataDto> GameDatas { get; set; } = new List<GameDataDto>();
    public string UserId { get; set; }
    [BindProperty]
    public int GameDataId { get; set; }
    [BindProperty]
    public AddCartItemDto AddCartItem { get; set; }
    public async Task<IActionResult> OnGetAsync()
    {
        UserId = "1f43468c-c467-4cdd-a02d-29bd888e09c8";
        
        var bonusResponse = await _httpClient.GetAsync("http://localhost:5294/api/Bonus/getAll");
        if (bonusResponse.IsSuccessStatusCode)
        {
            var bonusJson = await bonusResponse.Content.ReadAsStringAsync();
            Bonus = JsonSerializer.Deserialize<List<BonusDto>>(bonusJson, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
        }
        
        var gameDataResponse = await _httpClient.GetAsync($"http://localhost:5294/api/GameData/getAllByUserId/{UserId}");
        if (gameDataResponse.IsSuccessStatusCode)
        {
            var gameDataJson = await gameDataResponse.Content.ReadAsStringAsync();
            GameDatas = JsonSerializer.Deserialize<List<GameDataDto>>(gameDataJson, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
        }

        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
            return Page();
        
        var jsonData = JsonSerializer.Serialize(AddCartItem);
        var content  = new StringContent(jsonData, Encoding.UTF8, "application/json");
        var response = await _httpClient.PostAsync("http://localhost:5294/api/Cart/add", content);
        
        if (!response.IsSuccessStatusCode)
        {
            ModelState.AddModelError(string.Empty, "Cart update failed");
            return Page();
        }

        return RedirectToPage();
    }
}

STIVE.CL/STIVE.CL/Pages/Cart.cshtml
@page
@model STIVE.CL.Pages.CartModel

@{
    ViewData["Title"] = "Panier";
}

<div class="text-center" xmlns="http://www.w3.org/1999/html">
    <div class="image-container position-relative pt-5 pb-5">
        <img src="image/Table.png" class="img-fluid" alt="Livre" style="width: 100%;"/>
        <div class="position-absolute overlay-div" style="top: 12%; left: 6%; width: 87%; height: 82%;">
            <a asp-page="/Shop" id="cartButton">
                <img src="image/Bourse.png" class="img-fluid" alt="Bourse" style="position: absolute; top: 0px; right: 10px; width: 100px; cursor: pointer;"/>
            </a>
            <h2 class="text-decoration-underline mb-5">Panier</h2>
            @if (Model.UserCarts.Any())
            {
                @foreach (var cart in Model.UserCarts)
                {
                    <div class="card mb-4">
                        <div class="card-header bg-dark text-white">
                            <h4>Panier - Sauvegarde @cart.GameDataId</h4>
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered text-center">
                                <thead class="thead-dark">
                                <tr>
                                    <th>Bonus</th>
                                    <th>Quantité</th>
                                    <th>Prix</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach (var item in cart.CartItems)
                                {
                                    <tr>
                                        <td>@item.BonusName</td>
                                        <td>@item.Quantity</td>
                                        <td>@( (item.Quantity * item.BonusPrice).ToString("F2") ) €</td>
                                        <td>
                                            <form method="post" asp-page-handler="RemoveItem">
                                                <input type="hidden" name="UserId" value="@Model.UserId" />
                                                <input type="hidden" name="BonusId" value="@item.BonusId" />
                                                <input type="hidden" name="GameDataId" value="@cart.GameDataId" />
                                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Voulez-vous vraiment supprimer cet article du panier ?');">
                                                    Supprimer
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                }
                                </tbody>
                            </table>
                            <div class="d-flex justify-content-around">
                                <form method="post" asp-page-handler="Validate" class="d-inline-block">
                                    <input type="hidden" name="UserId" value="@Model.UserId" />
                                    <input type="hidden" name="GameDataId" value="@cart.GameDataId" />
                                    <button type="submit" class="btn btn-warning mt-3" onclick="return confirm('Voulez-vous vraiment valider ce panier ?');">Valider le panier</button>
                                </form>
                                <form method="post" asp-page-handler="ClearCart" class="d-inline-block">
                                    <input type="hidden" name="UserId" value="@Model.UserId" />
                                    <input type="hidden" name="GameDataId" value="@cart.GameDataId" />
                                    <button type="submit" class="btn btn-warning mt-3" onclick="return confirm('Voulez-vous vraiment supprimer ce panier ?');">Vider le panier</button>
                                </form>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <p class="text">Aucun panier trouvé</p>
            }
        </div>
    </div>
</div>

STIVE.CL/STIVE.CL/Pages/Classement.cshtml
@page
@model STIVE.CL.Pages.ClassementModel

@{
    ViewData["Title"] = "Classement";
}

<div class="text-center" xmlns="http://www.w3.org/1999/html">
    <div class="image-container position-relative pt-5 pb-5">
        <img src="image/Table.png" class="img-fluid" alt="Livre" style="width: 100%;"/>
        <div class="position-absolute overlay-div" style="top: 12%; left: 6%; width: 87%; height: 82%;">
            <h2 class="text-decoration-underline">Tableau des meilleurs vendeurs</h2>
            <br/>
            <table class="text-center w-100">
                <thead>
                <th>Classement</th>
                <th>Pseudo</th>
                <th>Nombre de gold</th>
                </thead>
                <tbody>
                @{
                    int rank = 1;
                    @foreach (var user in Model.Users)
                    {
                        <tr>
                            <td>@rank</td>
                            <td>@user.UserName</td>
                            <td>@user.Gold</td>
                        </tr>
                        rank++;
                    }
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

STIVE.CL/STIVE.CL/Pages/Game.cshtml
@page
@model STIVE.CL.Pages.GameModel

@{
    ViewData["Title"] = "Le jeu";
}

<div class="text-center" xmlns="http://www.w3.org/1999/html">
    <div class="image-container position-relative text-end pt-5">
        <img src="image/Title.png" class="img-fluid" alt="Livre" style="width: 85%; height: 100px"/>
        <div class="position-absolute overlay-div" style="top: 48%; left: auto; width: 90%; height: 30%;">
            <p>Devenez le plus grand alchimiste du royaume</p>
        </div>
    </div>
    <div class="image-container position-relative text-end">
        <img src="image/Mage.png" class="img-fluid position-absolute" style="left: -8%;" alt="Mage"/>
        <img src="image/PaperCarre.png" class="img-fluid ml-5" style="width: 70%" alt="Paper"/>
        <div class="position-absolute overlay-div text-center align-content-center" style="top: 5%; left: 34%; width: 62%; height: 90%;">
            <p>Reprenez la boutique familiale et faites honneur à votre ancêtre.</p><hr/>
            <p>Vendez des potions pour accroître vos gains.</p><hr/>
            <p>Investissez chez de nouveaux fournisseurs pour diversifier votre offre.</p><hr/>
            <p>Devenez le plus grand marchand de potions du royaume !</p>
        </div>
    </div>
</div>

STIVE.CL/STIVE.CL/Pages/Index.cshtml
@page
@model STIVE.CL.Pages.IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center" xmlns="http://www.w3.org/1999/html">
    <div class="image-container position-relative pt-5 pb-5">
        <img src="image/Book.png" class="img-fluid" alt="Livre" style="width: 100%;"/>
        <div class="position-absolute overlay-div" style="top: 16%; left: 11%; width: 36%; height: 66%;">
            <img src="image/PageAccueil.png" class="img-fluid mb-5" alt="Accueil" style="width: 100%"/>
            <img src="image/jeu.png" class="img-fluid mt-4" alt="Jeu" style="width: 100%"/>
        </div>
        <div class="position-absolute overlay-div align-content-center" style="top: 16%; left: 53%; width: 36%; height: 66%;">
            <p>Rejoignez l'aventure dès maintenant !</p>
            <br/><a href="#" download class="button">Jouer gratuitement</a>
            <br/><br/><br/><p>Déjà plus de @Model.UserCount joueurs</p>
        </div>
    </div>
</div>

STIVE.CL/STIVE.CL/Pages/Jeu.cshtml
@page
@model STIVE.CL.Pages.JeuModel

@{
    ViewData["Title"] = "Jeu";
}

<div class="text-center" xmlns="http://www.w3.org/1999/html">
    <div class="image-container position-relative text-end pt-5">
        <img src="image/Title.png" class="img-fluid" alt="Livre" style="width: 85%; height: 100px"/>
        <div class="position-absolute overlay-div" style="top: 48%; left: auto; width: 90%; height: 30%;">
            <p>Devenez le plus grand alchimiste du royaume</p>
        </div>
    </div>
    <div class="image-container position-relative text-end">
        <img src="image/Mage.png" class="img-fluid position-absolute" style="left: -8%;" alt="Mage"/>
        <img src="image/PaperCarre.png" class="img-fluid ml-5" style="width: 70%" alt="Paper"/>
        <div class="position-absolute overlay-div text-center align-content-center" style="top: 5%; left: 34%; width: 62%; height: 90%;">
            <p>Reprenez la boutique familiale et faites honneur à votre ancêtre.</p><hr/>
            <p>Vendez des potions pour accroître vos gains.</p><hr/>
            <p>Investissez chez de nouveaux fournisseurs pour diversifier votre offre.</p><hr/>
            <p>Devenez le plus grand marchand de potions du royaume !</p>
        </div>
    </div>
</div>

STIVE.CL/STIVE.CL/Pages/Login.cshtml
@page
@model STIVE.CL.Pages.LoginModel

@{
    ViewData["Title"] = "Login";
}

<div class="text-center" xmlns="http://www.w3.org/1999/html">
    <div class="image-container position-relative pt-5">
        <img src="image/PaperRectangle1.png" class="img-fluid" alt="Livre" style="width: 80%; height: fit-content"/>
        <div class="position-absolute overlay-div align-content-center" style="top: 18%; left: 10%; width: 81%; height: auto">
            <form method="post" class="w-100 d-flex flex-column align-items-center">
                <div class="form-group w-75 mb-2">
                    <label asp-for="userLoginDto.UserName">Identifiant</label>
                    <span asp-validation-for="userLoginDto.UserName" class="text-danger"></span>
                    <input asp-for="userLoginDto.UserName" class="form-control"/>
                </div>
                <div class="form-group w-75 mb-2">
                    <label asp-for="userLoginDto.Password">Mot de passe</label>
                    <span asp-validation-for="userLoginDto.Password" class="text-danger"></span>
                    <input asp-for="userLoginDto.Password" type="password" class="form-control"/>
                </div>
                <button type="submit" class="button m-2">Se connecter</button>
                <div>
                    <a asp-page="/register">Vous n'avez pas de compte ? Inscrivez-vous ICI !</a>
                </div>
            </form>
            @if (Model.ErrorMessage != null)
            {
            <p style="color:red;">@Model.ErrorMessage</p>
            }
        </div>
    </div>
</div>

@section Scripts
{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

STIVE.CL/STIVE.CL/Pages/Register.cshtml
@page
@model STIVE.CL.Pages.RegisterModel

@{
    ViewData["Title"] = "Register";
}

<div class="text-center" xmlns="http://www.w3.org/1999/html">
    <div class="image-container position-relative pt-5 mb-5">
        <img src="image/PaperRectangle1.png" class="img-fluid" alt="Livre" style="width: 80%; height: 830px"/>
        <div class="position-absolute overlay-div align-content-center" style="top: 18%; left: 10%; width: 81%; height: auto">
            <form method="post" class="w-100 d-flex flex-column align-items-center">
                <div class="form-group w-75 mb-2">
                    <label asp-for="UserRegister.UserName">Pseudo</label>
                    <span asp-validation-for="UserRegister.UserName" class="text-danger"></span>
                    <input asp-for="UserRegister.UserName" class="form-control"/>
                </div>
                <div class="form-group w-75 mb-2">
                    <label asp-for="UserRegister.Email">Email</label>
                    <span asp-validation-for="UserRegister.Email" class="text-danger"></span>
                    <input asp-for="UserRegister.Email" class="form-control"/>
                </div>
                <div class="form-group w-75 mb-2">
                    <label asp-for="UserRegister.PhoneNumber">Téléphone</label>
                    <span asp-validation-for="UserRegister.PhoneNumber" class="text-danger"></span>
                    <input asp-for="UserRegister.PhoneNumber" class="form-control"/>
                </div>
                <div class="form-group w-75 mb-2">
                    <label asp-for="UserRegister.Password">Mot de passe</label>
                    <span asp-validation-for="UserRegister.Password" class="text-danger"></span>
                    <input asp-for="UserRegister.Password" class="form-control" type="password"/>
                </div>
                <div class="form-group w-75 mb-2">
                    <label asp-for="UserRegister.ConfirmPassword">Confirmez le mot de passe</label>
                    <span asp-validation-for="UserRegister.ConfirmPassword" class="text-danger"></span>
                    <input asp-for="UserRegister.ConfirmPassword" class="form-control" type="password" />
                </div>
                <button type="submit" class="button m-2">Register</button>
                <div>
                    <a asp-page="/login">Déjà un compte ? Connectez vous ici !</a>
                </div>
            </form>
        </div>
    </div>
</div>